#  For more information about TARDIS pipelines, please refer to:
#
#    https://tardis-sn.github.io/tardis/development/continuous_integration.html

name: tests

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

  workflow_dispatch:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

env:
  XUVTOP: /tmp/chianti
  CHIANTI_DL_URL: https://download.chiantidatabase.org
  CHIANTI_DB_VER: CHIANTI_v9.0.1_database.tar.gz
  PYTEST_CORES: auto
  PYTEST_FLAGS: --remote-data --runslow --test-db=carsus-db/test_databases/test.db
                --refdata=carsus-refdata --cov=carsus --cov-report=xml
                --cov-report=html
  PYTEST_NB_FLAGS: --ignore-glob="**/*.py" --nb-test-files --nb-exec-timeout 600
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:

  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux
            prefix: /usr/share/miniconda/envs/carsus

          - os: macos-latest
            label: macOS
            prefix: /Users/runner/miniconda3/envs/carsus

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          repository: tardis-sn/carsus-db
          path: carsus-db
          lfs: false

      - run: |
          cd carsus-db
          git lfs install --skip-smudge
          git lfs pull --include="test_databases/test.db"

      - uses: actions/checkout@v2
        with:
          repository: tardis-sn/carsus-refdata
          path: carsus-refdata
          lfs: true

      - uses: actions/cache@v2
        with:
          path: ${{ env.XUVTOP }}
          key: ${{ runner.os }}-${{ env.CHIANTI_DB_VER }}
        id: chianti-cache

      - name: Download Chianti database
        run: |
            mkdir -p ${{ env.XUVTOP }}
            wget -q ${{ env.CHIANTI_DL_URL }}/${{ env.CHIANTI_DB_VER }} -O ${{ env.XUVTOP }}/chianti.tar.gz
            tar -zxf ${{ env.XUVTOP }}/chianti.tar.gz -C ${{ env.XUVTOP }}
        if: steps.chianti-cache.outputs.cache-hit != 'true'

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: carsus
            use-mamba: true

      - name: Set cache number
        run: echo "::set-output name=number::$(date +'%d%m')"
        id: cache-number

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ runner.os }}-conda-${{ hashFiles('carsus_env3.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: ${{ steps.cache-number.outputs.number }}
        id: conda-cache

      - name: Update environment
        run: mamba env update -n carsus -f carsus_env3.yml
        if: steps.conda-cache.outputs.cache-hit != 'true'

      - name: Install package
        run: pip install -e .

      - name: Run unit tests
        run: pytest carsus -n ${{ env.PYTEST_CORES }} ${{ env.PYTEST_FLAGS }}
#
#      - name: Run notebook tests
#        run: pytest carsus -n ${{ env.PYTEST_CORES }} ${{ env.PYTEST_NB_FLAGS }}
#        env:
#          CARSUS_REFDATA: ${{ github.workspace }}/carsus-refdata
#        if: runner.os == 'Linux'
#
#      - name: Upload to codecov.io
#        run: bash <(curl -s https://codecov.io/bash)
#        if: runner.os == 'Linux'
